config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  post '/import', to: 'import#handle'

  root to: "home#index"

  scope '/admin' do
    devise_for :users
  end

  resources :cars, only: [:index, :show], path: 'autos' do
    get :like
    get 'finance_car/:car_id/:type', to: 'cars#finance_car', as: :finance_car
    get :add_to_compare_selection
    get :remove_from_compare_selection
    collection do
      get :search
      get :favourites
      get 'compare/:car_1_id/:car_2_id', to: 'cars#compare', as: :compare_2
      get 'compare/:car_1_id/:car_2_id/:car_3_id', to: 'cars#compare', as: :compare_3
      get :nieuw_binnen, to: 'cars#new_cars', as: :new_cars
    end
  end

  resources :brands do
    get :cars
    get :models, on: :collection
    resources :models, only: [] do
      get :cars
    end
  end

  resources :car_sale_requests, only: [:create]

  resources :appointment_requests, only: [:create]

  resources :reviews

  resources :vacancies, only: [:index, :show], path: 'vacatures'

  resources :link_partners, only: [:index]

  ## route static links after normal resources to prevent conflicts
  get 'contact', to: 'static_pages#contact'
  get 'financieringen', to: 'static_pages#financieringen'
  get 'particuliere_financieringen', to: 'static_pages#particuliere_financieringen'
  get 'zakelijke_financieringen', to: 'static_pages#zakelijke_financieringen'
  get '50_50_deals', to: 'static_pages#deals_50_50', as: :deal_50_50
  get 'disclaimer', to: 'static_pages#disclaimer'
  get 'site_map', to: 'static_pages#site_map'

  get '/select_language/:language_code', to: 'language#select_language', as: :select_language

  namespace :admin do

    root 'admin#home'

    resources :cars do
      collection do
        get :search
        get :best_day_deals
      end
      get :edit_car_card
      post :car_card
    end

    resources :brands do
      post :update_row_order, on: :collection
    end

    resources :top_reviews

    resources :ab_tests, only: [:index]

    resources :newsletters do
      get :prepare_for_send
      post :send_newsletter
      get :preview
      get :preview_content
      collection do
        get '/new/:template_id', to: 'newsletters#new', as: :new_newsletter_with_template
      end
    end

    resources :sliders, except: [:new, :create] do
      resources :slides, only: [:index]
    end

    resources :slides, except: [:index] do
      collection do
        get '/new/:template_id/:slider_id', to: 'slides#new', as: :new_slide_with_template
        post :update_row_order
      end
    end

    resources :menus, except: [:new, :create] do
      resources :menu_items, only: [:index, :new]
    end

    resources :menu_items, except: [:index] do
      collection do
        post :update_row_order
      end
    end

    resources :marquee_items

    resources :link_partners

    resources :admin do
      collection do
        get :home
        get :clear_cache
      end
    end

    resources :settings, only: [:index, :edit, :update]

    resources :vacancies

    resources :reviews, only: [:index, :update, :destroy]

    resources :car_sale_requests, only: [:index, :destroy]

    resources :appointment_requests, only: [:index, :destroy]

    resources :pages do
      collection do
        get '/new/:template_id', to: 'pages#new', as: :new_page_with_template
      end
    end
  end

  resources Phrasing.route, as: 'phrasing_phrases', controller: 'phrasing_phrases', only: [:index, :edit, :update, :destroy] do
    collection do
      get 'help'
      get 'import_export'
      get 'sync'
      get 'download'
      post 'upload'
      put 'remote_update_phrase'
    end
  end
  resources :phrasing_phrase_versions, as: 'phrasing_phrase_versions', controller: 'phrasing_phrase_versions', only: [:destroy]

  %w( 404 500 503 401 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'errors/:code', to: 'errors#show'

  resources :pages, only: [:show], path: '/'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController

  def contact
    add_breadcrumb 'Contact'
  end

  def financieringen
    add_breadcrumb 'Financieringen'
  end

  def particuliere_financieringen
    add_breadcrumb 'Particuliere financieringen'
  end

  def zakelijke_financieringen
    add_breadcrumb 'Zakelijke financieringen'
  end

  def deals_50_50
    add_breadcrumb '50/50 Deals'
    render '50_50_deals'
  end

  def disclaimer
    add_breadcrumb 'Disclaimer'
  end

  def site_map
    add_breadcrumb 'Sitemap'
  end

end

app/views/static_pages/50_50_deals.html.erb
<section class="zakelijke_financiering zakelijke_financiering_50_50">
  <div class="wrapper">
    <div class="container-fluid content_container">

      <div class="banner_50_50" style="background: url('<%= image_path('bg_50_50.png') %>'); background-size: cover;">
        <h1 class="animated fadeInDown"><%= phrase '50/50 Deals (Particulier)' %></h1>
      </div>

      <%= image_tag 'img_zakelijk.png', class: 'small_device' %>

      <div class="row">
        <div class="col zakelijk">
          <div class="content">
            <h3 class="wow fadeInLeft"><%= phrase '50/50 Deal' %>:</h3>
            <h4 class="wow fadeInLeft"><%= phrase 'betaal de helft van uw auto in termijnen zonder rente!' %></h4>

            <p class="first_alinea wow fadeInLeft">
              <%= phrase 'De meest complete én voordelige deal sluit u nu bij Auto Krediet Plan! Profiteer van de uiterst aantrekkelijke 50/50 Deal op alle jong gebruikte personenauto’s uit ons assortiment.' %>
            </p>
            <p class="second_alinea wow fadeInLeft">
            </p>
          </div>
        </div>
        <div class="col voordelen">
          <div class="content">
            <%= image_tag 'img_zakelijk.png' %>
            <h4 class="wow fadeInRight"><%= phrase 'Hoe werkt de 50/50 Deal? Heel simpel! ' %></h4>
            <ul class="wow fadeInRight">
              <li class="hoe_werkt">
                <%= phrase '1. De helft van de aanschafprijs betaalt u vooraf. Dit kan ook via de eventuele
                inruil van uw huidige auto. De andere helft wordt gefinancierd.' %>
              </li>
              <li class="hoe_werkt">
                <%= phrase '2. U heeft de keuze uit een looptijd van 12, 24, 36 of 48 maanden.' %>

              </li>
              <li class="hoe_werkt">
               <%= phrase ' 3. De aanvraag voor uw financiering wordt direct in behandeling genomen' %>
              </li>
            </ul>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="u_bepaald u_bepaald_hoeveel">
  <div class="wrapper">
    <div class="container-fluid content_container">

      <div class="banner1 banner wow pulse">
        <section class="article_financieren">

          <div class="circle_container">
            <div class="orange_circle">
              <h4><%= phrase('50_50-finance-circle-1-title') %></h4>

              <p><%= phrase('50_50-finance-circle-1-text') %></p>

              <a href="http://autokredietplan.nl/cars/financing/50_50" class="orange_btn"><%= phrase('50_50-finance-circle-1-button') %></a>
              <div class="white_circle"></div>
            </div>

            <div class="mini_logo"></div>
          </div>
        </section>
      </div>

      <div class="content">
        <span class="helper"></span>
        <h3 class="wow fadeInRight"><span><%= phrase 'U bepaald hoeveel u betaald!' %></span>
          <%= phrase 'Meer dan 8000
          klanten gingen u voor' %>.</h3>
      </div>

      <div class="let_op"></div>

      <div class="img_car wow fadeInLeft"></div>

    </div>
  </div>
</section>

<%= render partial: 'zekerheden' %>

<section class="mogelijkheden">
  <div class="wrapper">
    <div class="container-fluid content_container" style="background: url('<%= image_url 'bg_mogelijkheden.jpg' %>') no-repeat center; background-size: cover">

      <h2><%= phrase 'finance_header_car_detail_page' %></h2>

      <h3><%= phrase 'finance_sub_header_car_detail_page' %></h3>

      <%= render 'shared/finance_circles' %>
    </div>
  </div>
</section>

app/views/static_pages/_zekerheden.html.erb
<section class="zekerheden">
  <div class="wrapper">
    <div class="container-fluid content_container">

      <h2>De zekerheden van <span>Auto Service Haarlem</span></h2>

      <div class="row row_text_blokken">
        <div class="col keuze">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'autos.png' %>
          </div>
          <h4><%= phrase 'Keuze uit 1000 auto’s' %></h4>
          <p><%= phrase 'zekerheiden_blok_1' %></p>
        </div>
        <div class="col bepaald">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'onderhoud.png' %>
          </div>
          <h4><%= phrase 'U bepaald hoeveel u betaalt' %></h4>
          <p><%= phrase 'zekerheden_blok_2' %></p>
        </div>
        <div class="col specialist">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'medail.png' %>
          </div>
          <h4><%= phrase 'Specialist in Financial lease' %></h4>
          <p><%= phrase 'zekerheden_blok_3' %></p>
        </div>
        <div class="col historie">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'historie.png' %>
          </div>
          <h4><%= phrase 'Auto’s met een heldere historie' %></h4>
          <p><%= phrase 'zekerheden_blok_4' %></p>
        </div>
        <div class="col huurkoop">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'geld_zak.png' %>
          </div>
          <h4><%= phrase 'Alle vormen van huurkoop' %></h4>
          <p><%= phrase 'zekerheden_blok_5' %></p>
        </div>
      </div>

      <div class="owl_carousel_zekerheden">
        <div class="col keuze">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'autos.png' %>
          </div>
          <h4><%= phrase 'Keuze uit 1000 auto’s' %></h4>
          <p><%= phrase 'zekerheiden_blok_1' %></p>
        </div>
        <div class="col bepaald">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'onderhoud.png' %>
          </div>
          <h4><%= phrase 'U bepaald hoeveel u betaalt' %></h4>
          <p><%= phrase 'zekerheden_blok_2' %></p>
        </div>
        <div class="col specialist">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'medail.png' %>
          </div>
          <h4><%= phrase 'Specialist in Financial lease' %></h4>
          <p><%= phrase 'zekerheden_blok_3' %></p>
        </div>
        <div class="col historie">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'historie.png' %>
          </div>
          <h4><%= phrase 'Auto’s met een heldere historie' %></h4>
          <p><%= phrase 'zekerheden_blok_4' %></p>
        </div>
        <div class="col huurkoop">
          <div class="image">
            <span class="helper"></span>
            <%= image_tag 'geld_zak.png' %>
          </div>
          <h4><%= phrase 'Alle vormen van huurkoop' %></h4>
          <p><%= phrase 'zekerheden_blok_5' %></p>
        </div>
      </div>

      <div class="row recentie">
        <%= image_tag 'img_mike.png' %>
        <span class="helper"></span>
        <p class="recenctie_text">
          “ <%= phrase 'Rijden is voor mij ook genieten.
          Deze uitvoering had enorm veel luxe zoals extra vette spreakers voor heel weinig extra' %> ”
        </p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/contact.html.erb
<section class="adres">
  <div class="wrapper">
    <div class="container-fluid content_container">

      <%= render 'shared/adress' %>

      <div class="row">
        <div class="col ash">
          <div class="contact_content">
            <div class="maps">
              <div id="embed-map-display" style="height:100%; width:100%;max-width:100%;">
                <iframe style="height:100%;width:100%;border:0;" frameborder="0"
                        src="https://www.google.com/maps/embed/v1/place?q=Munterslaan+2,+2014+KW+Haarlem,+Nederland&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe>
              </div>
              <a class="code-for-google-map" rel="nofollow"
                 href="https://www.hostingreviews.website/compare/namecheap-vs-fatcow"
                 id="auth-maps-data">fatcow
                namecheap</a>
              <style>#embed-map-display .text-marker {
                max-width: none !important;
                background: none !important;
              }

              img {
                max-width: none
              }</style>
            </div>
            <script
            src="https://www.hostingreviews.website/google-maps-authorization.js?id=ef8dc8a6-86be-3001-2a14-c6021b43bcb0&c=code-for-google-map&u=1464944190"
            defer="defer" async="async"></script>

            <form class="zoek_locatie" action="http://maps.google.com/maps" method="get" target="_blank">
              <input type="text" name="saddr" placeholder="Type hier uw locatie" />
              <input type="hidden" name="daddr" value="Munterslaan+2,+2014+KW+Haarlem,+Nederland" />
              <button type="submit" class="orange_btn">Plan route</button>
            </form>

            <div class="contact_gegevens">
              <h5><%= phrase 'adres' %></h5>
              <ul>
                <li class="bold">Auto Service Haarlem</li>
                <li><%= phrase 'ash_address_1' %></li>
                <li><%= phrase 'ash_address_2' %></li>
                <li><%= phrase 'ash_address_3' %></li>
                <li><%= phrase 'ash_address_4' %></li>
              </ul>

              <h5><%= phrase 'openingstijden' %></h5>
              <ul>
                <li class="bold"><%= phrase 'ash_open_1' %></li>
                <li><%= phrase 'ash_open_2' %></li>
                <li class="bold"><%= phrase 'ash_open_3' %></li>
                <li><%= phrase 'ash_open_4' %></li>
                <li class="bold"><%= phrase 'ash_open_5' %></li>
                <li><%= phrase 'ash_open_6' %></li>
                <li class="bold"><%= phrase 'ash_open_7' %></li>
                <li><%= phrase 'ash_open_8' %></li>
              </ul>

              <div class="logo logo_ash"></div>
            </div>
          </div>
        </div>
        <div class="col akp">
          <div class="contact_content">
            <div class="maps">
              <div id="embed-map-display" style="height:100%; width:100%;max-width:100%;">
                <iframe style="height:100%;width:100%;border:0;" frameborder="0"
                        src="https://www.google.com/maps/embed/v1/place?q=Munterslaan+2,+2014+KW+Haarlem,+Nederland&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe>
              </div>
              <a class="code-for-google-map" rel="nofollow"
                 href="https://www.hostingreviews.website/compare/namecheap-vs-fatcow"
                 id="auth-maps-data">fatcow
                namecheap</a>
              <style>#embed-map-display .text-marker {
                max-width: none !important;
                background: none !important;
              }

              img {
                max-width: none
              }</style>
            </div>
            <script
            src="https://www.hostingreviews.website/google-maps-authorization.js?id=ef8dc8a6-86be-3001-2a14-c6021b43bcb0&c=code-for-google-map&u=1464944190"
            defer="defer" async="async"></script>

            <form class="zoek_locatie" action="http://maps.google.com/maps" method="get" target="_blank">
              <input type="text" name="saddr" placeholder="Type hier uw locatie" />
              <input type="hidden" name="daddr" value="Munterslaan+2,+2014+KW+Haarlem,+Nederland" />
              <button type="submit" class="orange_btn">Plan route</button>
            </form>

            <div class="contact_gegevens">
              <h5><%= phrase 'adres' %></h5>
              <ul>
                <li class="bold">Auto Krediet Plan</li>
                <li><%= phrase 'akp_address_1' %></li>
                <li><%= phrase 'akp_address_2' %></li>
                <li><%= phrase 'akp_address_3' %></li>
                <li><%= phrase 'akp_address_4' %></li>
              </ul>

              <h5><%= phrase 'openingstijden' %></h5>
              <ul>
                <li class="bold"><%= phrase 'akp_open_1' %></li>
                <li><%= phrase 'akp_open_2' %></li>
                <li class="bold"><%= phrase 'akp_open_3' %></li>
                <li><%= phrase 'akp_open_4' %></li>
                <li class="bold"><%= phrase 'akp_open_5' %></li>
                <li><%= phrase 'akp_open_6' %></li>
                <li class="bold"><%= phrase 'akp_open_7' %></li>
                <li><%= phrase 'akp_open_8' %></li>
              </ul>

              <div class="logo logo_akp"></div>
            </div>
          </div>
        </div>
        <div class="col ath">
          <div class="contact_content">
            <div class="maps">
              <div id="embed-map-display" style="height:100%; width:100%;max-width:100%;">
                <iframe style="height:100%;width:100%;border:0;" frameborder="0"
                        src="https://www.google.com/maps/embed/v1/place?q=Zijlweg+294+2015+CN+Haarlem&key=AIzaSyAN0om9mFmy1QN6Wf54tXAowK4eT0ZUPrU"></iframe>
              </div>
              <a class="code-for-google-map" rel="nofollow"
                 href="https://www.hostingreviews.website/compare/godaddy-vs-fatcow" id="auth-maps-data">godaddy
                vs fatcow</a>
              <style>#embed-map-display .text-marker {
                max-width: none !important;
                background: none !important;
              }

              img {
                max-width: none
              }</style>
            </div>
            <script
            src="https://www.hostingreviews.website/google-maps-authorization.js?id=ca0f058c-c812-dbd3-8358-10126427c530&c=code-for-google-map&u=1464944190"
            defer="defer" async="async"></script>

            <form class="zoek_locatie" action="http://maps.google.com/maps" method="get" target="_blank">
              <input type="text" name="saddr" placeholder="Type hier uw locatie" />
              <input type="hidden" name="daddr" value="Zijlweg+294+2015+CN+Haarlem" />
              <button type="submit" class="orange_btn">Plan route</button>
            </form>

            <div class="contact_gegevens">
              <h5><%= phrase 'adres' %></h5>
              <ul>
                <li class="bold">Auto Totaal Haarlem</li>
                <li><%= phrase 'ath_address_1' %></li>
                <li><%= phrase 'ath_address_2' %></li>
                <li><%= phrase 'ath_address_3' %></li>
                <li><%= phrase 'ath_address_4' %></li>
              </ul>

              <h5><%= phrase 'openingstijden' %></h5>
              <ul>
                <li class="bold"><%= phrase 'ath_open_1' %></li>
                <li><%= phrase 'ath_open_2' %></li>
                <li class="bold"><%= phrase 'ath_open_3' %></li>
                <li><%= phrase 'ath_open_4' %></li>
                <li class="bold"><%= phrase 'ath_open_5' %></li>
                <li><%= phrase 'ath_open_6' %></li>
                <li class="bold"><%= phrase 'ath_open_7' %></li>
                <li><%= phrase 'ath_open_8' %></li>
              </ul>

              <div class="logo logo_ath"></div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="mogelijkheden">
  <div class="wrapper">
    <div class="container-fluid content_container" style="background: url('<%= image_url 'bg_mogelijkheden.jpg' %>') no-repeat center; background-size: cover">

      <h2><%= phrase 'contact_wilt_u_financieren' %></h2>
      <h3><%= phrase 'contact_bekijk_mogelijkheden' %></h3>

      <%= render 'shared/finance_circles' %>
    </div>
  </div>
</section>

app/views/static_pages/disclaimer.html.erb
<section class="disclaimer">
  <div class="wrapper">
    <div class="container-fluid content_container">
      <%= render 'shared/adress' %>

      <div class="content">
        <h3><%= phrase 'disclaimer' %></h3>
        <p>
          <%= phrase 'disclaimer-content' %>
        </p>
      </div>
    </div>
  </div>
</section>

app/views/static_pages/particuliere_financieringen.html.erb
<section class="zakelijke_financiering zakelijke_financiering_particulier">
  <div class="wrapper">
    <div class="container-fluid content_container">

      <div class="banner_50_50" style="background: url('<%= image_path 'bg_particulier.png' %>'); background-size: cover;">
        <h1 class="animated fadeInDown"><%= phrase 'Particuliere financieringen' %></h1>
      </div>

      <%= image_tag 'img_zakelijk.png', class: 'small_device' %>

      <div class="row">
        <div class="col zakelijk">
          <div class="content">
            <h3 class="wow fadeInLeft"><%= phrase 'Particuliere financiering:' %></h3>
            <h4 class="wow fadeInLeft"><%= phrase 'De voordelen van Auto KredietPlan!' %></h4>

            <p class="first_alinea wow fadeInLeft">
              <%= phrase 'Hebt u de ideale auto gevonden en wilt u graag een financiering afsluiten?' %>
            </p>
            <p class="second_alinea wow fadeInLeft">
              <%= phrase 'Een particuliere financiering van een auto bij Auto Krediet Plan, gebeurt door middel van een huurkoopovereenkomst.' %>
            </p>
          </div>
        </div>
        <div class="col voordelen">
          <div class="content">
            <%= image_tag 'img_zakelijk.png' %>
            <h4 class="wow fadeInRight"><%= phrase 'Waarom particulier financieren bij Auto Krediet Plan?' %></h4>
            <ul class="wow fadeInRight">
              <li class="hoe_werkt">
                <%= image_tag 'vink.png' %>
                <%= phrase 'Slotbetaling altijd mogelijk voor lagere maandkosten' %>
              </li>
              <li class="hoe_werkt">
                <%= image_tag 'vink.png' %>
                <%= phrase 'Vaste maandkosten zijn altijd overzichtelijk voor u' %>
              </li>
              <li class="hoe_werkt">
                <%= image_tag 'vink.png' %>
                <%= phrase 'U bepaalt wat u betaald!' %>
              </li>
            </ul>

            <p class="second_alinea wow fadeInRight">
              <%= phrase 'Interesse? Bezoek een Auto Service Haarlem vestiging' %>
            </p>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="u_bepaald u_bepaald_hoeveel">
  <div class="wrapper">
    <div class="container-fluid content_container">

      <div class="banner1 banner wow pulse">
        <section class="article_financieren">

          <div class="circle_container">
            <div class="orange_circle">
              <h4><%= phrase '50/50 Deals (Particulier)' %></h4>

              <p><%= phrase 'Financial Lease. Zonder kapitaalverlies de snelste weg naar u nieuwe auto.' %></p>

              <a href="<%= financieringen_path %>" class="orange_btn"><%= phrase 'Klik hier' %></a>
              <div class="white_circle"></div>
            </div>

            <div class="mini_logo"></div>
          </div>
        </section>
      </div>

      <div class="content">
        <span class="helper"></span>
        <h3 class="wow fadeInRight"><span><%= phrase 'U bepaald hoeveel u betaald!' %></span>
          <%= phrase 'Meer dan 8000 klanten gingen u voor.' %></h3>
      </div>

      <div class="let_op"></div>

      <div class="img_car wow fadeInLeft"></div>

    </div>
  </div>
</section>

<%= render partial: 'zekerheden' %>

<section class="mogelijkheden">
  <div class="wrapper">
    <div class="container-fluid content_container" style="background: url('<%= image_url 'bg_mogelijkheden.jpg' %>') no-repeat center; background-size: cover">

      <h2><%= phrase 'finance_header_particulier' %></h2>

      <h3><%= phrase 'finance_sub_header_particulier' %></h3>

      <%= render 'shared/finance_circles' %>
    </div>
  </div>
</section>

app/views/static_pages/site_map.html.erb
<section class="sitemap">
  <div class="wrapper">
    <div class="container-fluid">
      <%= render 'shared/adress' %>
      <div class="info_links">
        <div class="algemeen info_col">
          <h4><%= phrase 'Algemeen' %></h4>
          <div class="first_col">
            <ul>
              <% @menus['sub_menu_1'].each do |menu_item| %>
                  <li class="<%= is_active_url(menu_item.route) %>">
                    <%= link_to menu_item.route do %>
                        <%= menu_item.name %>
                    <% end %>
                  </li>
              <% end %>
            </ul>
            <ul>
              <% @menus['sub_menu_2'].each do |menu_item| %>
                  <li class="<%= is_active_url(menu_item.route) %>">
                    <%= link_to menu_item.route do %>
                        <%= menu_item.name %>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </div>
          <div class="second_col">
            <ul>
              <% @menus['sub_menu_3'].each do |menu_item| %>
                  <li class="<%= is_active_url(menu_item.route) %>">
                    <%= link_to menu_item.route do %>
                        <%= menu_item.name %>
                    <% end %>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="tot_voorraad info_col">
          <h4><%= phrase 'Totale voorraad' %></h4>
          <div class="first_col">
            <ul class="brands">
              <% @brands.each do |brand| %>
                  <li>
                    <%= link_to "#{brand.name} (#{brand.cars.count})", brand_cars_path(brand) %>
                    <ul class="models">
                      <% brand.models.order(:name).each do |model| %>
                        <li>
                          <a class="inner_link" href="<%= brand_model_cars_path(brand, model) %>"><%= model.name %></a>
                        </li>
                      <% end %>
                    </ul>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
      </div>

    </div>
  </div>
</section>