config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  post '/import', to: 'import#handle'

  root to: "home#index"

  scope '/admin' do
    devise_for :users
  end

  resources :cars, only: [:index, :show], path: 'autos' do
    get :like
    get 'finance_car/:car_id/:type', to: 'cars#finance_car', as: :finance_car
    get :add_to_compare_selection
    get :remove_from_compare_selection
    collection do
      get :search
      get :favourites
      get 'compare/:car_1_id/:car_2_id', to: 'cars#compare', as: :compare_2
      get 'compare/:car_1_id/:car_2_id/:car_3_id', to: 'cars#compare', as: :compare_3
      get :nieuw_binnen, to: 'cars#new_cars', as: :new_cars
    end
  end

  resources :brands do
    get :cars
    get :models, on: :collection
    resources :models, only: [] do
      get :cars
    end
  end

  resources :car_sale_requests, only: [:create]

  resources :appointment_requests, only: [:create]

  resources :reviews

  resources :vacancies, only: [:index, :show], path: 'vacatures'

  resources :link_partners, only: [:index]

  ## route static links after normal resources to prevent conflicts
  get 'contact', to: 'static_pages#contact'
  get 'financieringen', to: 'static_pages#financieringen'
  get 'particuliere_financieringen', to: 'static_pages#particuliere_financieringen'
  get 'zakelijke_financieringen', to: 'static_pages#zakelijke_financieringen'
  get '50_50_deals', to: 'static_pages#deals_50_50', as: :deal_50_50
  get 'disclaimer', to: 'static_pages#disclaimer'
  get 'site_map', to: 'static_pages#site_map'

  get '/select_language/:language_code', to: 'language#select_language', as: :select_language

  namespace :admin do

    root 'admin#home'

    resources :cars do
      collection do
        get :search
        get :best_day_deals
      end
      get :edit_car_card
      post :car_card
    end

    resources :brands do
      post :update_row_order, on: :collection
    end

    resources :top_reviews

    resources :ab_tests, only: [:index]

    resources :newsletters do
      get :prepare_for_send
      post :send_newsletter
      get :preview
      get :preview_content
      collection do
        get '/new/:template_id', to: 'newsletters#new', as: :new_newsletter_with_template
      end
    end

    resources :sliders, except: [:new, :create] do
      resources :slides, only: [:index]
    end

    resources :slides, except: [:index] do
      collection do
        get '/new/:template_id/:slider_id', to: 'slides#new', as: :new_slide_with_template
        post :update_row_order
      end
    end

    resources :menus, except: [:new, :create] do
      resources :menu_items, only: [:index, :new]
    end

    resources :menu_items, except: [:index] do
      collection do
        post :update_row_order
      end
    end

    resources :marquee_items

    resources :link_partners

    resources :admin do
      collection do
        get :home
        get :clear_cache
      end
    end

    resources :settings, only: [:index, :edit, :update]

    resources :vacancies

    resources :reviews, only: [:index, :update, :destroy]

    resources :car_sale_requests, only: [:index, :destroy]

    resources :appointment_requests, only: [:index, :destroy]

    resources :pages do
      collection do
        get '/new/:template_id', to: 'pages#new', as: :new_page_with_template
      end
    end
  end

  resources Phrasing.route, as: 'phrasing_phrases', controller: 'phrasing_phrases', only: [:index, :edit, :update, :destroy] do
    collection do
      get 'help'
      get 'import_export'
      get 'sync'
      get 'download'
      post 'upload'
      put 'remote_update_phrase'
    end
  end
  resources :phrasing_phrase_versions, as: 'phrasing_phrase_versions', controller: 'phrasing_phrase_versions', only: [:destroy]

  %w( 404 500 503 401 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'errors/:code', to: 'errors#show'

  resources :pages, only: [:show], path: '/'

end

app/models/marquee_item.rb
class MarqueeItem < ActiveRecord::Base
end

app/controllers/admin/marquee_items_controller.rb
module Admin
  class MarqueeItemsController < AdminBaseController
    before_action :set_marquee_item, only: [:show, :edit, :update, :destroy]

    # GET /marquee_items
    # GET /marquee_items.json
    def index
      @marquee_items = MarqueeItem.all
    end

    # GET /marquee_items/1
    # GET /marquee_items/1.json
    def show
    end

    # GET /marquee_items/new
    def new
      @marquee_item = MarqueeItem.new
    end

    # GET /marquee_items/1/edit
    def edit
    end

    # POST /marquee_items
    # POST /marquee_items.json
    def create
      @marquee_item = MarqueeItem.new(marquee_item_params)

      respond_to do |format|
        if @marquee_item.save
          format.html { redirect_to admin_marquee_items_path, notice: 'Marquee item was successfully created.' }
          format.json { render :show, status: :created, location: @marquee_item }
        else
          format.html { render :new }
          format.json { render json: @marquee_item.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /marquee_items/1
    # PATCH/PUT /marquee_items/1.json
    def update
      respond_to do |format|
        if @marquee_item.update(marquee_item_params)
          format.html { redirect_to admin_marquee_items_path, notice: 'Marquee item was successfully updated.' }
          format.json { render :show, status: :ok, location: @marquee_item }
        else
          format.html { render :edit }
          format.json { render json: @marquee_item.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /marquee_items/1
    # DELETE /marquee_items/1.json
    def destroy
      @marquee_item.destroy
      respond_to do |format|
        format.html { redirect_to admin_marquee_items_path, notice: 'Marquee item was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
    # Use callbacks to share common setup or constraints between actions.
    def set_marquee_item
      @marquee_item = MarqueeItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def marquee_item_params
      params.require(:marquee_item).permit(:title, :link)
    end
  end
end

app/views/admin/marquee_items/_form.html.erb
<div class="form-group">

  <%= f.label :title, 'Titel', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: 'form-control' %>
  </div>

</div>

<div class="form-group">

  <%= f.label :link, 'Link', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :link, class: 'form-control' %>
  </div>

</div>

<div class="hr-line-dashed"></div>
<div class="form-group">
  <div class="col-sm-4 col-sm-offset-2">
    <%= link_to 'Annuleren', admin_marquee_items_path, class: 'btn btn-white' %>
    <%= f.submit 'Opslaan', class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/marquee_items/_marquee_item.html.erb
<tr class="item" data-item-id="<%= marquee_item.id %>">
  <td><%= marquee_item.title %></td>
  <td><%= marquee_item.link %></td>
  <td>
    <%= link_to 'Aanpassen', edit_admin_marquee_item_path(marquee_item), class: 'btn btn-primary' %>
    <%= link_to 'Delete', admin_marquee_item_path(marquee_item), method: :delete, class: 'btn btn-danger' %>
  </td>
</tr>

app/views/admin/marquee_items/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Marquee item aanpassen</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Marquee items', admin_marquee_items_path %>
      </li>
      <li class="active">
        <strong><%= @marquee_item.title %> Aanpassen</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5><%= @marquee_item.title %> Aanpassen</h5>
        </div>
        <div class="ibox-content">
          <%= form_for @marquee_item, url: admin_marquee_item_path(@marquee_item), method: :put, html: {class: 'form-horizontal'} do |f| %>
            <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>

    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript">


      $(function () {

        $('.i-checks').iCheck({
          checkboxClass: 'icheckbox_square-green',
          radioClass: 'iradio_square-green',
        });

        $('.summernote').summernote();

      });

    </script>

<% end %>

app/views/admin/marquee_items/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Marquee items</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li class="active">
        <strong>Marquee items</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Marquee items</h5>
          <div class="ibox-tools">
            <%= link_to new_admin_marquee_item_path do %>
                <i class="fa fa-plus"></i><span> Nieuw item</span>
            <% end %>
          </div>
        </div>
        <div class="ibox-content">

          <table class="table table-striped"  >
            <thead>
            <tr>
              <th>Titel</th>
              <th>Link</th>
              <th>Acties</th>
            </tr>
            </thead>

            <tbody>
            <%= render @marquee_items %>
            </tbody>
          </table>

        </div>
      </div>
    </div>

  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>
    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript" charset="utf-8">
      $(document).ready(function () {
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

        elems.forEach(function (html) {
          var switchery = new Switchery(html);
        });

        $('.js-switch').on('change', function () {
          $(this).parents('form').submit();
        });

      });
    </script>
<% end %>

app/views/admin/marquee_items/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Nieuw Marquee item</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Marquee items', admin_marquee_items_path %>
      </li>
      <li class="active">
        <strong>Nieuw Marquee item</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nieuw Marquee item</h5>
        </div>
        <div class="ibox-content">
          <%= form_for @marquee_item, url: admin_marquee_items_path, method: :post, html: {class: 'form-horizontal'} do |f| %>
            <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>

    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript">


      $(function () {

        $('.i-checks').iCheck({
          checkboxClass: 'icheckbox_square-green',
          radioClass: 'iradio_square-green',
        });

        $('.summernote').summernote();

      });

    </script>

<% end %>