config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  post '/import', to: 'import#handle'

  root to: "home#index"

  scope '/admin' do
    devise_for :users
  end

  resources :cars, only: [:index, :show], path: 'autos' do
    get :like
    get 'finance_car/:car_id/:type', to: 'cars#finance_car', as: :finance_car
    get :add_to_compare_selection
    get :remove_from_compare_selection
    collection do
      get :search
      get :favourites
      get 'compare/:car_1_id/:car_2_id', to: 'cars#compare', as: :compare_2
      get 'compare/:car_1_id/:car_2_id/:car_3_id', to: 'cars#compare', as: :compare_3
      get :nieuw_binnen, to: 'cars#new_cars', as: :new_cars
    end
  end

  resources :brands do
    get :cars
    get :models, on: :collection
    resources :models, only: [] do
      get :cars
    end
  end

  resources :car_sale_requests, only: [:create]

  resources :appointment_requests, only: [:create]

  resources :reviews

  resources :vacancies, only: [:index, :show], path: 'vacatures'

  resources :link_partners, only: [:index]

  ## route static links after normal resources to prevent conflicts
  get 'contact', to: 'static_pages#contact'
  get 'financieringen', to: 'static_pages#financieringen'
  get 'particuliere_financieringen', to: 'static_pages#particuliere_financieringen'
  get 'zakelijke_financieringen', to: 'static_pages#zakelijke_financieringen'
  get '50_50_deals', to: 'static_pages#deals_50_50', as: :deal_50_50
  get 'disclaimer', to: 'static_pages#disclaimer'
  get 'site_map', to: 'static_pages#site_map'

  get '/select_language/:language_code', to: 'language#select_language', as: :select_language

  namespace :admin do

    root 'admin#home'

    resources :cars do
      collection do
        get :search
        get :best_day_deals
      end
      get :edit_car_card
      post :car_card
    end

    resources :brands do
      post :update_row_order, on: :collection
    end

    resources :top_reviews

    resources :ab_tests, only: [:index]

    resources :newsletters do
      get :prepare_for_send
      post :send_newsletter
      get :preview
      get :preview_content
      collection do
        get '/new/:template_id', to: 'newsletters#new', as: :new_newsletter_with_template
      end
    end

    resources :sliders, except: [:new, :create] do
      resources :slides, only: [:index]
    end

    resources :slides, except: [:index] do
      collection do
        get '/new/:template_id/:slider_id', to: 'slides#new', as: :new_slide_with_template
        post :update_row_order
      end
    end

    resources :menus, except: [:new, :create] do
      resources :menu_items, only: [:index, :new]
    end

    resources :menu_items, except: [:index] do
      collection do
        post :update_row_order
      end
    end

    resources :marquee_items

    resources :link_partners

    resources :admin do
      collection do
        get :home
        get :clear_cache
      end
    end

    resources :settings, only: [:index, :edit, :update]

    resources :vacancies

    resources :reviews, only: [:index, :update, :destroy]

    resources :car_sale_requests, only: [:index, :destroy]

    resources :appointment_requests, only: [:index, :destroy]

    resources :pages do
      collection do
        get '/new/:template_id', to: 'pages#new', as: :new_page_with_template
      end
    end
  end

  resources Phrasing.route, as: 'phrasing_phrases', controller: 'phrasing_phrases', only: [:index, :edit, :update, :destroy] do
    collection do
      get 'help'
      get 'import_export'
      get 'sync'
      get 'download'
      post 'upload'
      put 'remote_update_phrase'
    end
  end
  resources :phrasing_phrase_versions, as: 'phrasing_phrase_versions', controller: 'phrasing_phrase_versions', only: [:destroy]

  %w( 404 500 503 401 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'errors/:code', to: 'errors#show'

  resources :pages, only: [:show], path: '/'

end

app/models/setting.rb
class Setting < ActiveRecord::Base

  def partial_name
    'text_field'
  end

  def display_value
    self.value
  end

  def to_partial_path
    'settings/setting'
  end

  def template_value
    self.value
  end

  def self.get(setting_name)
    self.find_by_setting(setting_name).try(:template_value) rescue nil
  end
end

app/models/settings/checkbox_field.rb
class Settings::CheckboxField < Setting

  def value
    ActiveRecord::Type::Boolean.new.type_cast_from_database(super)
  end

  def partial_name
    'checkbox_field'
  end

  def display_value
    self.value == true ? 'Aan' : 'Uit'
  end

end

app/models/settings/image_field.rb
module Settings
  class ImageField < Setting
    mount_uploader :value, SettingImageUploader

    def partial_name
      'image_field'
    end

    def display_value
      ActionController::Base.helpers.image_tag(self.value.try(:thumb))
    end

    def template_value
      self.value.try(:url)
    end
  end
end

app/models/settings/page_field.rb
class Settings::PageField < Setting

  belongs_to :page, foreign_key: :value

  def display_value
    self.page.try(:title)
  end

  def partial_name
    'page_field'
  end

  def template_value
    self.page
  end

end

app/models/settings/text_area.rb
module Settings
  class TextArea < Setting

    def partial_name
      'text_area'
    end

    def display_value
      ActionController::Base.helpers.truncate(ActionController::Base.helpers.strip_tags(value), length: 80)
    end
  end
end

app/models/settings/text_field.rb
class Settings::TextField < Setting
end

app/controllers/admin/settings_controller.rb
class Admin::SettingsController < Admin::AdminBaseController

  def index
    @settings = Setting.all.order(:name)
  end
  
  def edit
    @setting = Setting.find(params[:id])
  end

  def update
    @setting = Setting.find(params[:id])
    respond_to do |format|
      if @setting.update(setting_params)
        format.html { redirect_to admin_settings_path, notice: 'Setting is aangepast.' }
      else
        format.html { render :edit }
      end
    end
  end

  private

  def setting_params
    params.require(:setting).permit(:id, :value)
  end

end

app/views/admin/settings/_form.html.erb
<style>
  .note-editor {
    min-height: 0;
  }
</style>

<div class="form-group">
  <%= f.label :name, 'Setting', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :name, class: 'form-control', disabled: true %>
  </div>
</div>

<div class="hr-line-dashed"></div>

<%= render 'admin/settings/setting_values/' + f.object.partial_name, {f: f} %>

<div class="hr-line-dashed"></div>

<div class="form-group">
  <div class="col-sm-10 col-sm-push-2">
    <%= link_to 'Annuleren', admin_settings_path, class: 'btn btn-white' %>
    <%= f.submit 'Opslaan', class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/settings/_setting.html.erb
<tr class="item">
  <td><%= setting.name %></td>
  <td><%= setting.display_value %></td>
  <td>
    <%= link_to 'Aanpassen', edit_admin_setting_path(setting), class: 'btn btn-primary' %>
  </td>
</tr>

app/views/admin/settings/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Setting "<%= @setting.name %>" aanpassen</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Settings', admin_settings_path %>
      </li>
      <li class="active">
        <strong>Setting "<%= @setting.name %>" aanpassen</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Setting "<%= @setting.name %>" aanpassen</h5>
        </div>
        <div class="ibox-content">
          <%= form_for @setting, as: :setting, url: admin_setting_path(@setting), method: :put, html: {class: 'form-horizontal'} do |f| %>
              <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>

    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript">


      $(function () {

        $('.i-checks').iCheck({
          checkboxClass: 'icheckbox_square-green',
          radioClass: 'iradio_square-green',
        });

        $('.summernote').summernote();

      });

    </script>

<% end %>

app/views/admin/settings/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Settings</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li class="active">
        <strong>Settings</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Settings</h5>
        </div>
        <div class="ibox-content">

          <table class="table table-striped"  >
            <thead>
            <tr>
              <th>Setting</th>
              <th>Waarde</th>
              <th>Acties</th>
            </tr>
            </thead>

            <tbody>
            <%= render @settings %>
            </tbody>
          </table>

        </div>
      </div>
    </div>

  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>
    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript" charset="utf-8">
      $(document).ready(function () {
        var elems = Array.prototype.slice.call(document.querySelectorAll('.js-switch'));

        elems.forEach(function (html) {
          var switchery = new Switchery(html);
        });

        $('.js-switch').on('change', function () {
          $(this).parents('form').submit();
        });

      });
    </script>
<% end %>