config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/rails_admin', as: 'rails_admin'
  post '/import', to: 'import#handle'

  root to: "home#index"

  scope '/admin' do
    devise_for :users
  end

  resources :cars, only: [:index, :show], path: 'autos' do
    get :like
    get 'finance_car/:car_id/:type', to: 'cars#finance_car', as: :finance_car
    get :add_to_compare_selection
    get :remove_from_compare_selection
    collection do
      get :search
      get :favourites
      get 'compare/:car_1_id/:car_2_id', to: 'cars#compare', as: :compare_2
      get 'compare/:car_1_id/:car_2_id/:car_3_id', to: 'cars#compare', as: :compare_3
      get :nieuw_binnen, to: 'cars#new_cars', as: :new_cars
    end
  end

  resources :brands do
    get :cars
    get :models, on: :collection
    resources :models, only: [] do
      get :cars
    end
  end

  resources :car_sale_requests, only: [:create]

  resources :appointment_requests, only: [:create]

  resources :reviews

  resources :vacancies, only: [:index, :show], path: 'vacatures'

  resources :link_partners, only: [:index]

  ## route static links after normal resources to prevent conflicts
  get 'contact', to: 'static_pages#contact'
  get 'financieringen', to: 'static_pages#financieringen'
  get 'particuliere_financieringen', to: 'static_pages#particuliere_financieringen'
  get 'zakelijke_financieringen', to: 'static_pages#zakelijke_financieringen'
  get '50_50_deals', to: 'static_pages#deals_50_50', as: :deal_50_50
  get 'disclaimer', to: 'static_pages#disclaimer'
  get 'site_map', to: 'static_pages#site_map'

  get '/select_language/:language_code', to: 'language#select_language', as: :select_language

  namespace :admin do

    root 'admin#home'

    resources :cars do
      collection do
        get :search
        get :best_day_deals
      end
      get :edit_car_card
      post :car_card
    end

    resources :brands do
      post :update_row_order, on: :collection
    end

    resources :top_reviews

    resources :ab_tests, only: [:index]

    resources :newsletters do
      get :prepare_for_send
      post :send_newsletter
      get :preview
      get :preview_content
      collection do
        get '/new/:template_id', to: 'newsletters#new', as: :new_newsletter_with_template
      end
    end

    resources :sliders, except: [:new, :create] do
      resources :slides, only: [:index]
    end

    resources :slides, except: [:index] do
      collection do
        get '/new/:template_id/:slider_id', to: 'slides#new', as: :new_slide_with_template
        post :update_row_order
      end
    end

    resources :menus, except: [:new, :create] do
      resources :menu_items, only: [:index, :new]
    end

    resources :menu_items, except: [:index] do
      collection do
        post :update_row_order
      end
    end

    resources :marquee_items

    resources :link_partners

    resources :admin do
      collection do
        get :home
        get :clear_cache
      end
    end

    resources :settings, only: [:index, :edit, :update]

    resources :vacancies

    resources :reviews, only: [:index, :update, :destroy]

    resources :car_sale_requests, only: [:index, :destroy]

    resources :appointment_requests, only: [:index, :destroy]

    resources :pages do
      collection do
        get '/new/:template_id', to: 'pages#new', as: :new_page_with_template
      end
    end
  end

  resources Phrasing.route, as: 'phrasing_phrases', controller: 'phrasing_phrases', only: [:index, :edit, :update, :destroy] do
    collection do
      get 'help'
      get 'import_export'
      get 'sync'
      get 'download'
      post 'upload'
      put 'remote_update_phrase'
    end
  end
  resources :phrasing_phrase_versions, as: 'phrasing_phrase_versions', controller: 'phrasing_phrase_versions', only: [:destroy]

  %w( 404 500 503 401 ).each do |code|
    get code, :to => "errors#show", :code => code
  end

  get 'errors/:code', to: 'errors#show'

  resources :pages, only: [:show], path: '/'

end

app/models/newsletter.rb
class Newsletter < ActiveRecord::Base
  belongs_to :newsletter_template
  has_many :newsletter_values, dependent: :destroy

  accepts_nested_attributes_for :newsletter_values

  scope :newsletter_includes, -> { includes(:newsletter_values, :newsletter_template) }

  def self.get_lists
    gibbon = Gibbon::Request.new
    lists = gibbon.lists.retrieve
    lists = lists['lists']
    lists.map do |list|
      [
          "#{list['name']} (#{list['stats']['member_count']})",
          list['id']
      ]
    end
  end

  def create_campaign(list_id)
    gibbon = Gibbon::Request.new
    recipients = {
        list_id: list_id
    }
    settings = {
        subject_line: self.subject,
        title: self.title,
        from_name: 'Auto Service Haarlem',
        reply_to: 'info@autoservicehaarlem.nl'
    }

    body = {
        type: "regular",
        recipients: recipients,
        settings: settings
    }

    begin
      response = gibbon.campaigns.create(body: body)
      update!(campaign_id: response['id'])
      self.update_campaign
      self.send_campaign
    rescue Gibbon::MailChimpError => e
      puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
      raise e
    end
  end

  def update_campaign
    gibbon = Gibbon::Request.new
    body = {
        html: self.generate_html,
    }
    begin
      response = gibbon.campaigns(self.campaign_id).content.upsert(body: body)
      puts response.inspect
    rescue Gibbon::MailChimpError => e
      puts "Houston, we have a problem: #{e.message} - #{e.raw_body}"
      raise e
    end
  end

  def send_campaign
    gibbon = Gibbon::Request.new
    gibbon.campaigns(self.campaign_id).actions.send.create
  end

  def generate_html
    ApplicationController.new.render_to_string(template: 'admin/newsletters/templates/' + self.newsletter_template.template, locals: template_variables, layout: false)
  end

  def template_variables
    newsletter_values.includes(:newsletter_template_value).index_by { |value| value.newsletter_template_value.option_name.to_sym }
  end

  def get_campaign_statistics
    gibbon = Gibbon::Request.new
    gibbon.campaigns(self.campaign_id).retrieve rescue nil
  end

end

app/controllers/admin/newsletters_controller.rb
class Admin::NewslettersController < Admin::AdminBaseController

  def index
    @newsletters = Newsletter.newsletter_includes.all.order('created_at DESC').page(params[:page])
  end

  def prepare_for_send
    @newsletter = Newsletter.find(params[:newsletter_id])
  end

  def send_newsletter
    @newsletter = Newsletter.find(params[:newsletter_id])
    if @newsletter.present? && params[:list_id].present?
      @newsletter.create_campaign(params[:list_id])
      flash[:notice] = 'De nieuwsbrief is verstuurd'
      redirect_to :admin_newsletters
    end
  end

  def new
    @newsletter = Newsletter.new
    begin
      newsletter_template = NewsletterTemplate.find(params[:template_id])
      @newsletter.newsletter_template = newsletter_template if newsletter_template.present?
      newsletter_template.newsletter_template_values.each do |newsletter_template_value|
        @newsletter.newsletter_values << NewsletterValue.new(newsletter_template_value: newsletter_template_value, type: newsletter_template_value.option_type)
      end
    rescue Exception => e
      Rails.logger.debug e.message
      Rails.logger.debug e.backtrace.join("\n")
      flash[:errors] = 'Het geselecteerde nieuwsbrief template bestaat niet, mocht dit probleem aanhouden neem dan contact op met fabian@oldharlem.nl of mverhaar@merqwaardig.com.'
      redirect_to admin_newsletters_path
    end
  end

  def create
    begin
      @newsletter = Newsletter.create(newsletter_params)
      if @newsletter.valid?
        flash[:notice] = 'Nieuwsbrief is aangemaakt'
        redirect_to admin_newsletters_path
      else
        puts @newsletter.errors.full_messages
        flash[:error] = @newsletter.errors.full_messages.to_sentence
        render :new
      end
    rescue Exception => e
      flash[:error] = 'Er ging iets fout, check je invoer en probeer het nogmaals'
      logger.debug e.message
      redirect_to :back
    end
  end

  def edit
    @newsletter = Newsletter.find(params[:id])
  end

  def update
    @newsletter = Newsletter.find(params[:id])
    begin
      @newsletter.update(newsletter_params)
      if @newsletter.valid?
        flash[:notice] = 'Nieuwsbrief is aangepast'
        redirect_to admin_newsletters_path
      else
        puts @newsletter.errors.full_messages
        flash[:error] = @newsletter.errors.full_messages.to_sentence
        render :edit
      end
    rescue Exception => e
      flash[:error] = 'Er ging iets fout, check je invoer en probeer het nogmaals'
      logger.debug e.message
      logger.debug e.backtrace.join('\n')
      render :edit
    end
  end

  def preview
    @newsletter = Newsletter.find(params[:newsletter_id])
  end

  def preview_content
    @newsletter = Newsletter.find(params[:newsletter_id])
    template_variables = @newsletter.template_variables
    render 'admin/newsletters/templates/' + @newsletter.newsletter_template.template, layout: false, locals: template_variables
  end

  def destroy
    if Newsletter.find(params[:id]).destroy
      flash[:notice] = 'Nieuwsbrief is verwijderd'
    else
      flash[:error] = 'Niewsbrief kon niet verwijderd worden'
    end
    redirect_to admin_newsletters_path
  end

  private

  def newsletter_params
    params.require(:newsletter).permit(:id, :title, :subject, :newsletter_template_id, :row_order_position, newsletter_values_attributes: [:id, :value, :type, :newsletter_template_value_id, value: []])
  end
  
end

app/views/admin/newsletters/_form.html.erb
<style>
  .note-editor {
    min-height: 0;
  }
</style>

<%= f.hidden_field :newsletter_template_id %>

<div class="form-group">
  <%= f.label :title, 'Titel', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :title, class: 'form-control' %>
  </div>
</div>

<div class="form-group">
  <%= f.label :subject, 'Onderwerp', class: 'col-sm-2 control-label' %>
  <div class="col-sm-10">
    <%= f.text_field :subject, class: 'form-control' %>
  </div>
</div>

<div class="hr-line-dashed"></div>


<%= f.fields_for :newsletter_values, f.object.newsletter_values, class: 'col-sm-12' do |ff| %>
  <%= render 'admin/newsletters/newsletter_value_fields', f: ff %>
<% end %>


<div class="hr-line-dashed"></div>

<div class="form-group">
  <div class="col-sm-10 col-sm-push-2">
    <%= link_to 'Annuleren', admin_newsletters_path, class: 'btn btn-white' %>
    <%= f.submit 'Opslaan', class: 'btn btn-primary' %>
  </div>
</div>

app/views/admin/newsletters/_newsletter.html.erb
<tr>
  <td><%= newsletter.title %></td>
  <td><%= newsletter.subject %></td>
  <td><%= newsletter.created_at.strftime('%Y-%m-%d - %H:%M') %></td>
  <td><%= newsletter.updated_at.strftime('%Y-%m-%d - %H:%M') %></td>
  <td>
    <%= link_to 'Aanpassen', newsletter.campaign_id.present? ? '#' : edit_admin_newsletter_path(newsletter), class: 'btn btn-primary', disabled: newsletter.campaign_id.present? %>
    <%= link_to 'Verstuur', newsletter.campaign_id.present? ? '#' : admin_newsletter_prepare_for_send_path(newsletter), class: 'btn btn-success', disabled: newsletter.campaign_id.present? %>
    <%= link_to 'Voorbeeld', admin_newsletter_preview_path(newsletter), class: 'btn btn-default' %>
    <%= link_to 'Delete', admin_newsletter_path(newsletter), class: 'btn btn-danger', method: :delete %>
  </td>
</tr>

app/views/admin/newsletters/_newsletter_value_fields.html.erb
<%= f.hidden_field :newsletter_template_value_id %>
<%= f.hidden_field :type %>

<%= render 'admin/newsletters/newsletter_values/'+f.object.partial_name, {f: f} %>

app/views/admin/newsletters/_template_preview.html.erb
<%= image_tag template.image, width: '100%' %>

app/views/admin/newsletters/edit.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Nieuwsbrief "<%= @newsletter.title %>" aanpassen</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Nieuwsbrieven', admin_newsletters_path %>
      </li>
      <li class="active">
        <strong>Nieuwsbrief "<%= @newsletter.title %>" aanpassen</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-8">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nieuwsbrief "<%= @newsletter.title %>" aanpassen</h5>
        </div>
        <div class="ibox-content">
          <%= form_for @newsletter, url: admin_newsletter_path(@newsletter), method: :put, html: {class: 'form-horizontal'} do |f| %>
              <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Gekozen template</h5>
        </div>
        <div class="ibox-content">
          <%= render 'template_preview', template: @newsletter.newsletter_template %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>

    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript">


      $(function () {

        $('.i-checks').iCheck({
          checkboxClass: 'icheckbox_square-green',
          radioClass: 'iradio_square-green',
        });

        $('.summernote').summernote();

      });

    </script>

<% end %>

app/views/admin/newsletters/index.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Nieuwsbrieven</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li class="active">
        <strong>Nieuwsbrieven</strong>
      </li>
    </ol>
  </div>
  <div class="col-lg-2">

  </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nieuwsbrieven (<%= @newsletters.total_count %>)</h5>
          <div class="ibox-tools">
            <a class="dropdown-toggle btn btn-default" data-toggle="dropdown" href="#">
              <i class="fa fa-plus"></i><span> Nieuwe nieuwsbrief</span>
            </a>
            <ul class="dropdown-menu dropdown-user">
              <% NewsletterTemplate.all.each do |template| %>
                  <li>
                    <%= link_to template.name, new_newsletter_with_template_admin_newsletters_path(template) %>
                  </li>
              <% end %>
            </ul>
          </div>
        </div>
        <div class="ibox-content">

          <table class="table">
            <thead>
            <tr>
              <th>Titel</th>
              <th>Onderwerp</th>
              <th>Aanmaak datum</th>
              <th>Laatst aangepast</th>
              <th>Acties</th>
            </tr>
            </thead>

            <tbody>
            <%= render @newsletters %>
            </tbody>
          </table>

          <%= paginate @newsletters, theme: 'twitter-bootstrap-3', :pagination_class => "pagination-small pagination-centered" %>

        </div>
      </div>
    </div>

  </div>
</div>

app/views/admin/newsletters/new.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Nieuwe nieuwsbrief</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Nieuwsbrieven', admin_newsletters_path %>
      </li>
      <li class="active">
        <strong>Nieuwe nieuwsbrief</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-8">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nieuwe nieuwsbrief</h5>
        </div>
        <div class="ibox-content">
          <%= form_for @newsletter, url: admin_newsletters_path, method: :post, html: {class: 'form-horizontal'} do |f| %>
              <%= render 'form', f: f %>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-lg-4">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Gekozen template</h5>
        </div>
        <div class="ibox-content">
          <%= render 'template_preview', template: @newsletter.newsletter_template %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>

    <%= javascript_include_tag 'admin/forms' %>

    <script type="text/javascript">


      $(function () {

        $('.i-checks').iCheck({
          checkboxClass: 'icheckbox_square-green',
          radioClass: 'iradio_square-green',
        });

        $('.summernote').summernote();

      });

    </script>

<% end %>

app/views/admin/newsletters/prepare_for_send.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Nieuwsbrief "<%= @newsletter.title %>" aanpassen</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Nieuwsbrieven', admin_newsletters_path %>
      </li>
      <li class="active">
        <strong>Nieuwsbrief "<%= @newsletter.title %>" versturen</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nieuwsbrief "<%= @newsletter.title %>" versturen</h5>
        </div>
        <div class="ibox-content">
          <%= form_tag admin_newsletter_send_newsletter_path(@newsletter), method: :post, class: 'form-horizontal' do %>
              <div class="form-group">
                <%= label_tag :list_id, 'Mailchimp lijsten', class: 'col-sm-2 control-label' %>
                <div class="col-sm-10">
                  <%= select_tag :list_id, options_for_select(Newsletter.get_lists), class: 'form-control' %>
                </div>
              </div>
              <div class="hr-line-dashed"></div>

              <div class="form-group">
                <div class="col-sm-10 col-sm-push-2">
                  <%= link_to 'Annuleren', admin_newsletters_path, class: 'btn btn-white' %>
                  <%= submit_tag 'Versturen', class: 'btn btn-primary' %>
                </div>
              </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>

<% content_for :head do %>
    <%= stylesheet_link_tag 'admin/forms' %>
<% end %>

<% content_for :javascript do %>

    <%= javascript_include_tag 'admin/forms' %>

<% end %>

app/views/admin/newsletters/preview.html.erb
<div class="row wrapper border-bottom white-bg page-heading">
  <div class="col-lg-10">
    <h2>Nieuwsbrief "<%= @newsletter.title %>" preview</h2>
    <ol class="breadcrumb">
      <li>
        <a href="<%= url_for admin_root_path %>">Home</a>
      </li>
      <li>
        <%= link_to 'Nieuwsbrieven', admin_newsletters_path %>
      </li>
      <li class="active">
        <strong>Nieuwsbrief "<%= @newsletter.title %>" preview</strong>
      </li>
    </ol>
  </div>
</div>

<div class="wrapper wrapper-content animated fadeInRight">
  <div class="row">
    <div class="col-lg-12">
      <div class="ibox float-e-margins">
        <div class="ibox-title">
          <h5>Nieuwsbrief "<%= @newsletter.title %>" preview</h5>
          <div class="ibox-tools">
            <%= link_to 'Verstuur', @newsletter.campaign_id.present? ? '#' : admin_newsletter_prepare_for_send_path(@newsletter), class: 'btn btn-success', disabled: @newsletter.campaign_id.present? %>
          </div>
        </div>
        <div class="ibox-content">
          <iframe src="<%= admin_newsletter_preview_content_path(@newsletter) %>" frameborder="0" width="100%" onload="resizeIframe(this)"></iframe>
        </div>
      </div>
    </div>
  </div>
</div>

<script language="javascript" type="text/javascript">
  function resizeIframe(obj) {
    obj.style.height = obj.contentWindow.document.body.scrollHeight + 'px';
  }
</script>